version: "3.9"

services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: docker-wordpress-1
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: steve
      WORDPRESS_DB_PASSWORD: steve
      WORDPRESS_DB_NAME: chirostretch
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
    volumes:
      # NATIVE DOCKER VOLUME (FAST)
      - wordpress-data:/var/www/html

      # ONLY MOUNT WHAT YOU NEED TO EDIT
      - ./wp-overrides/themes/chirostretch:/var/www/html/wp-content/themes/chirostretch
      - ./wp-overrides/plugins/mu-plugins:/var/www/html/wp-content/mu-plugins

    networks:
      - chiro_net

  nginx:
    image: nginx:latest
    container_name: docker-nginx-1
    ports:
      - "8080:80"
    depends_on:
      - wordpress
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - wordpress-data:/var/www/html
    networks:
      - chiro_net

  db:
    image: mysql:8.0
    container_name: docker-db-1
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chirostretch
      MYSQL_USER: steve
      MYSQL_PASSWORD: steve
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - chiro_net

  wpcli:
    image: wordpress:cli
    container_name: docker-wpcli-1
    depends_on:
      - wordpress
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: steve
      WORDPRESS_DB_PASSWORD: steve
      WORDPRESS_DB_NAME: chirostretch
    volumes:
      - wordpress-data:/var/www/html
      - ./wp-overrides/themes/chirostretch:/var/www/html/wp-content/themes/chirostretch
      - ./wp-overrides/plugins/mu-plugins:/var/www/html/wp-content/mu-plugins
    networks:
      - chiro_net

volumes:
  wordpress-data:
  db-data:

networks:
  chiro_net:
